<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-5KMFOFH9" failures="1" tests="16" name="Test" time="23.264" errors="0" timestamp="2025-03-18T21:06:26 IST">
  <testcase classname="com.TestNG.BasicScenario.TestDemo1_priority_description" name="registerTest" time="0.012"/>
  <testcase classname="com.TestNG.BasicScenario.TestDemo1_priority_description" name="loginTest" time="0.001"/>
  <testcase classname="com.TestNG.BasicScenario.TestDemo1_priority_description" name="searchProductTest" time="0.002"/>
  <testcase classname="com.TestNG.BasicScenario.TestDemo1_priority_description" name="addToCartTest" time="0.001"/>
  <testcase classname="com.TestNG.BasicScenario.TestDemo2_invocationCount" name="registerTest" time="0.001"/>
  <testcase classname="com.TestNG.BasicScenario.TestDemo2_invocationCount" name="loginTest" time="0.001"/>
  <testcase classname="com.TestNG.BasicScenario.TestDemo2_invocationCount" name="loginTest" time="0.001"/>
  <testcase classname="com.TestNG.BasicScenario.TestDemo2_invocationCount" name="loginTest" time="0.001"/>
  <testcase classname="com.TestNG.BasicScenario.TestDemo3_timeouts" name="testcase1" time="4.014"/>
  <testcase classname="com.TestNG.BasicScenario.TestDemo3_timeouts" name="testcase2" time="5.012">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.TestNG.BasicScenario.TestDemo3_timeouts.testcase2() didn&amp;apos;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.TestNG.BasicScenario.TestDemo3_timeouts.testcase2() didn't finish within the time-out 5000
at java.base@17.0.2/java.lang.Thread.sleep(Native Method)
at app//com.TestNG.BasicScenario.TestDemo3_timeouts.testcase2(TestDemo3_timeouts.java:24)
at java.base@17.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- testcase2 -->
  <testcase classname="com.TestNG.BasicScenario.TestDemo4_disableTestFromCurrentExecution" name="regiterTest" time="0.001"/>
  <testcase classname="com.TestNG.BasicScenario.TestDemo4_disableTestFromCurrentExecution" name="loginTest" time="0.0"/>
  <testcase classname="com.TestNG.BasicScenario.TestDemo4_disableTestFromCurrentExecution" name="searchProductTest" time="0.002"/>
  <testcase classname="com.TestNG.BasicScenario.TestDemo4_disableTestFromCurrentExecution" name="addTocartTest" time="0.001"/>
  <testcase classname="com.TestNG.BasicScenario.TestDemo5_Usingxmldisabletest" name="chromeTest" time="7.047"/>
  <testcase classname="com.TestNG.BasicScenario.TestDemo5_Usingxmldisabletest" name="edgeTest" time="7.054"/>
  <testcase classname="com.TestNG.BasicScenario.TestDemo4_disableTestFromCurrentExecution" name="logoutTest" time="0.0">
    <ignored/>
  </testcase> <!-- logoutTest -->
  <testcase classname="com.TestNG.BasicScenario.TestDemo5_Usingxmldisabletest" name="firefoxTest" time="0.0">
    <ignored/>
  </testcase> <!-- firefoxTest -->
</testsuite> <!-- Test -->
